version: '3.8'

services:
  app:
    build: .
    ports:
      - "4500:4500"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=mqtt_predictions
      - POSTGRES_USER=james
      - POSTGRES_PASSWORD=miguel
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mqtt_predictions
      - POSTGRES_USER=james
      - POSTGRES_PASSWORD=miguel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    external: true
